/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Gnosis_Old",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Gnosis_Old__factory>;
    getContractFactory(
      name: "GnosisUntitled",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GnosisUntitled__factory>;
    getContractFactory(
      name: "SafeFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeFactory__factory>;

    getContractAt(
      name: "Gnosis_Old",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Gnosis_Old>;
    getContractAt(
      name: "GnosisUntitled",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.GnosisUntitled>;
    getContractAt(
      name: "SafeFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.SafeFactory>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
