/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as gnosisOldSol from "./Gnosis_old.sol";
export type { gnosisOldSol };
export type { GnosisUntitled } from "./GnosisUntitled";
export type { SafeFactory } from "./SafeFactory";
export * as factories from "./factories";
export type { Gnosis_Old } from "./Gnosis_old.sol/Gnosis_Old";
export { Gnosis_Old__factory } from "./factories/Gnosis_old.sol/Gnosis_Old__factory";
export { GnosisUntitled__factory } from "./factories/GnosisUntitled__factory";
export { SafeFactory__factory } from "./factories/SafeFactory__factory";
