/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as gnosisOldSol from "./Gnosis_old.sol";
export { GnosisUntitled__factory } from "./GnosisUntitled__factory";
export { SafeFactory__factory } from "./SafeFactory__factory";
